#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-$SCRIPT_DIR/cluster.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "env file not found: $ENV_FILE"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

if [[ -z "${REPO_DIR:-}" ]]; then
  echo "REPO_DIR is required"
  exit 1
fi

mkdir -p "$REPO_DIR/configs"
OUT="$REPO_DIR/configs/node-${NODE_ID}.yaml"

cat >"$OUT" <<EOF
# generated by deploy/gen-node-config.sh
node_id: ${NODE_ID}
listen_addr: "${NODE_LISTEN_ADDR}"
project_peers:
EOF

IFS=',' read -r -a peers <<< "${NODE_PEERS}"
for peer in "${peers[@]}"; do
  p="$(echo "$peer" | xargs)"
  [[ -z "$p" ]] && continue
  echo "  - $p" >>"$OUT"
done

echo "written: $OUT"

